/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Wed May 14 18:07:03 2014
**      by: Qt User Interface Compiler version 4.8.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTextBrowser>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>
#include "qwt_compass.h"
#include "qwt_dial.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionQuit;
    QWidget *centralWidget;
    QLabel *hostLabel;
    QLabel *portLabel;
    QPushButton *pushButtonChangeHost;
    QPushButton *pushButtonStart;
    QLabel *windSpeedLabel;
    QLabel *windSpeedData;
    QLabel *windDirLabel;
    QLabel *windDirData;
    QLabel *airTempLabel;
    QLabel *airTempData;
    QLabel *dpTempData;
    QLabel *dpTempLabel;
    QLabel *rhPercentLabel;
    QLabel *rhPercentData;
    QLabel *baroPressData;
    QLabel *baroPressLabel;
    QLabel *windSpeedMinData;
    QLabel *windSpeedMaxData;
    QLabel *windDirMinData;
    QLabel *windDirMaxData;
    QLabel *airTempMinData;
    QLabel *airTempMaxData;
    QLabel *dpTempMinData;
    QLabel *dpTempMaxData;
    QLabel *rhPercentMinData;
    QLabel *rhPercentMaxData;
    QLabel *baroPressMinData;
    QLabel *baroPressMaxData;
    QPushButton *pushButtonWindSpd;
    QPushButton *pushButtonWindDir;
    QPushButton *pushButtonAirT;
    QPushButton *pushButtonDpT;
    QPushButton *pushButtonRhP;
    QPushButton *pushButtonBaro;
    QwtDial *Dial;
    QwtCompass *Compass;
    QwtCompass *CompassCmgT;
    QwtDial *DialBoatSpd;
    QLabel *boatVmgKMinData;
    QLabel *boatVmgKData;
    QLabel *boatVmgKMaxData;
    QLabel *baroPressLabel_4;
    QPushButton *pushButtonBoatVmgK;
    QPushButton *pushButtonBoatCmgT;
    QLabel *boatCmgTData;
    QLabel *boatCmgTMaxData;
    QLabel *boatCmgTMinData;
    QLabel *baroPressLabel_5;
    QLabel *baroPressLabel_6;
    QLabel *relWindDirMinData;
    QwtCompass *CompassRelWind;
    QPushButton *pushButtonRelWindDir;
    QLabel *relWindDirData;
    QLabel *relWindDirMaxData;
    QLabel *boatHdgMData;
    QLabel *boatHdgMMaxData;
    QwtCompass *CompassMagHdg;
    QLabel *baroPressLabel_7;
    QPushButton *pushButtonBoatHdgM;
    QLabel *boatHdgMMinData;
    QwtDial *DialRelWindSpd;
    QLabel *windSpeedLabel_2;
    QLabel *relWindSpeedMaxData;
    QLabel *relWindSpeedMinData;
    QLabel *relWindSpeedData;
    QPushButton *pushButtonRelWindSpd;
    QLabel *utcTimeVal;
    QLabel *baroPressLabel_8;
    QLabel *utcTimeVal_2;
    QPushButton *pushButtonWindSpdAlarm;
    QLineEdit *lineEditWindSpdLow;
    QLineEdit *lineEditWindSpdHigh;
    QLineEdit *lineEditBoatHdgHigh;
    QPushButton *pushButtonBoatHdgAlarm;
    QLineEdit *lineEditBoatHdgLow;
    QLineEdit *lineEditWindDirLow;
    QLineEdit *lineEditWindDirHigh;
    QPushButton *pushButtonWindDirAlarm;
    QRadioButton *radioButtonWindAlarm;
    QRadioButton *radioButtonWindDirAlarm;
    QRadioButton *radioButtonBoatHdgAlarm;
    QLineEdit *lineEditBoatCmgLow;
    QLineEdit *lineEditBoatCmgHigh;
    QPushButton *pushButtonBoatCmgAlarm;
    QPushButton *pushButtonBoatSogAlarm;
    QLineEdit *lineEditBoatSogLow;
    QLineEdit *lineEditBoatSogHigh;
    QRadioButton *radioButtonBoatCmgAlarm;
    QRadioButton *radioButtonBoatSogAlarm;
    QPushButton *pushButtonRelWindDirAlarm;
    QLineEdit *lineEditRelWindDirLow;
    QLineEdit *lineEditRelWindDirHigh;
    QLineEdit *lineEditRelWindSpdHigh;
    QPushButton *pushButtonRelWindSpdAlarm;
    QLineEdit *lineEditRelWindSpdLow;
    QRadioButton *radioButtonRelWindSpdAlarm;
    QRadioButton *radioButtonRelWindDirAlarm;
    QLineEdit *lineEditBoatSogLow_4;
    QPushButton *pushButtonWaterT;
    QLabel *waterTempMaxData;
    QLabel *waterTempLabel;
    QLabel *waterTempMinData;
    QLabel *waterTempData;
    QLabel *waterDepthData;
    QLabel *waterDepthMaxData;
    QPushButton *pushButtonWaterD;
    QLabel *waterTempLabel_2;
    QLabel *waterDepthMinData;
    QLabel *baroPressLabel_9;
    QLabel *baroPressLabel_10;
    QPushButton *pushButtonGlobalReset;
    QLabel *globalResetLabel;
    QLabel *globalResetVal;
    QTextBrowser *textBrowserBaro;
    QLabel *baroHourlyLabel;
    QLabel *positionLatDData;
    QLabel *windSpeedLabel_3;
    QLabel *positionLonDData;
    QLabel *positionLatMData;
    QLabel *positionLonMData;
    QLabel *windSpeedLabel_4;
    QLabel *windSpeedLabel_5;
    QLabel *windSpeedLabel_6;
    QLineEdit *lineEditRefPosLatM;
    QLineEdit *lineEditRefPosLatD;
    QLineEdit *lineEditRefPosLonM;
    QLineEdit *lineEditRefPosLonD;
    QPushButton *pushButtonSetRefPosHere;
    QLabel *positionDistanceF;
    QLabel *windSpeedLabel_7;
    QLineEdit *lineEditPositionHigh;
    QLineEdit *lineEditPositionLow;
    QPushButton *pushButtonPositionAlarm;
    QLabel *windSpeedLabel_8;
    QLabel *positionMaxDistanceF;
    QLabel *windSpeedLabel_9;
    QLabel *windSpeedLabel_10;
    QLabel *positionNSDistanceF;
    QLabel *positionWEDistanceF;
    QMenuBar *menuBar;
    QMenu *menuProgram;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1297, 809);
        QFont font;
        font.setPointSize(12);
        MainWindow->setFont(font);
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QString::fromUtf8("actionQuit"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        hostLabel = new QLabel(centralWidget);
        hostLabel->setObjectName(QString::fromUtf8("hostLabel"));
        hostLabel->setGeometry(QRect(1190, 50, 101, 16));
        portLabel = new QLabel(centralWidget);
        portLabel->setObjectName(QString::fromUtf8("portLabel"));
        portLabel->setGeometry(QRect(1190, 70, 101, 20));
        pushButtonChangeHost = new QPushButton(centralWidget);
        pushButtonChangeHost->setObjectName(QString::fromUtf8("pushButtonChangeHost"));
        pushButtonChangeHost->setGeometry(QRect(1090, 90, 161, 25));
        pushButtonStart = new QPushButton(centralWidget);
        pushButtonStart->setObjectName(QString::fromUtf8("pushButtonStart"));
        pushButtonStart->setGeometry(QRect(1090, 20, 131, 25));
        pushButtonStart->setCheckable(true);
        pushButtonStart->setChecked(false);
        windSpeedLabel = new QLabel(centralWidget);
        windSpeedLabel->setObjectName(QString::fromUtf8("windSpeedLabel"));
        windSpeedLabel->setGeometry(QRect(0, 210, 131, 16));
        windSpeedData = new QLabel(centralWidget);
        windSpeedData->setObjectName(QString::fromUtf8("windSpeedData"));
        windSpeedData->setGeometry(QRect(130, 210, 71, 16));
        windDirLabel = new QLabel(centralWidget);
        windDirLabel->setObjectName(QString::fromUtf8("windDirLabel"));
        windDirLabel->setGeometry(QRect(210, 210, 161, 16));
        windDirData = new QLabel(centralWidget);
        windDirData->setObjectName(QString::fromUtf8("windDirData"));
        windDirData->setGeometry(QRect(370, 210, 71, 16));
        airTempLabel = new QLabel(centralWidget);
        airTempLabel->setObjectName(QString::fromUtf8("airTempLabel"));
        airTempLabel->setGeometry(QRect(410, 310, 111, 16));
        airTempData = new QLabel(centralWidget);
        airTempData->setObjectName(QString::fromUtf8("airTempData"));
        airTempData->setGeometry(QRect(520, 310, 81, 16));
        dpTempData = new QLabel(centralWidget);
        dpTempData->setObjectName(QString::fromUtf8("dpTempData"));
        dpTempData->setGeometry(QRect(750, 620, 81, 16));
        dpTempLabel = new QLabel(centralWidget);
        dpTempLabel->setObjectName(QString::fromUtf8("dpTempLabel"));
        dpTempLabel->setGeometry(QRect(630, 620, 101, 16));
        rhPercentLabel = new QLabel(centralWidget);
        rhPercentLabel->setObjectName(QString::fromUtf8("rhPercentLabel"));
        rhPercentLabel->setGeometry(QRect(870, 620, 141, 16));
        rhPercentData = new QLabel(centralWidget);
        rhPercentData->setObjectName(QString::fromUtf8("rhPercentData"));
        rhPercentData->setGeometry(QRect(1010, 620, 71, 16));
        baroPressData = new QLabel(centralWidget);
        baroPressData->setObjectName(QString::fromUtf8("baroPressData"));
        baroPressData->setGeometry(QRect(530, 620, 101, 16));
        baroPressLabel = new QLabel(centralWidget);
        baroPressLabel->setObjectName(QString::fromUtf8("baroPressLabel"));
        baroPressLabel->setGeometry(QRect(410, 620, 121, 16));
        windSpeedMinData = new QLabel(centralWidget);
        windSpeedMinData->setObjectName(QString::fromUtf8("windSpeedMinData"));
        windSpeedMinData->setGeometry(QRect(30, 230, 81, 16));
        windSpeedMaxData = new QLabel(centralWidget);
        windSpeedMaxData->setObjectName(QString::fromUtf8("windSpeedMaxData"));
        windSpeedMaxData->setGeometry(QRect(130, 230, 71, 16));
        windDirMinData = new QLabel(centralWidget);
        windDirMinData->setObjectName(QString::fromUtf8("windDirMinData"));
        windDirMinData->setGeometry(QRect(250, 230, 71, 16));
        windDirMaxData = new QLabel(centralWidget);
        windDirMaxData->setObjectName(QString::fromUtf8("windDirMaxData"));
        windDirMaxData->setGeometry(QRect(370, 230, 71, 16));
        airTempMinData = new QLabel(centralWidget);
        airTempMinData->setObjectName(QString::fromUtf8("airTempMinData"));
        airTempMinData->setGeometry(QRect(430, 330, 91, 20));
        airTempMaxData = new QLabel(centralWidget);
        airTempMaxData->setObjectName(QString::fromUtf8("airTempMaxData"));
        airTempMaxData->setGeometry(QRect(520, 330, 91, 20));
        dpTempMinData = new QLabel(centralWidget);
        dpTempMinData->setObjectName(QString::fromUtf8("dpTempMinData"));
        dpTempMinData->setGeometry(QRect(650, 640, 91, 16));
        dpTempMaxData = new QLabel(centralWidget);
        dpTempMaxData->setObjectName(QString::fromUtf8("dpTempMaxData"));
        dpTempMaxData->setGeometry(QRect(750, 640, 91, 16));
        rhPercentMinData = new QLabel(centralWidget);
        rhPercentMinData->setObjectName(QString::fromUtf8("rhPercentMinData"));
        rhPercentMinData->setGeometry(QRect(890, 640, 91, 16));
        rhPercentMaxData = new QLabel(centralWidget);
        rhPercentMaxData->setObjectName(QString::fromUtf8("rhPercentMaxData"));
        rhPercentMaxData->setGeometry(QRect(1010, 640, 71, 20));
        baroPressMinData = new QLabel(centralWidget);
        baroPressMinData->setObjectName(QString::fromUtf8("baroPressMinData"));
        baroPressMinData->setGeometry(QRect(430, 640, 101, 20));
        baroPressMaxData = new QLabel(centralWidget);
        baroPressMaxData->setObjectName(QString::fromUtf8("baroPressMaxData"));
        baroPressMaxData->setGeometry(QRect(530, 640, 101, 16));
        pushButtonWindSpd = new QPushButton(centralWidget);
        pushButtonWindSpd->setObjectName(QString::fromUtf8("pushButtonWindSpd"));
        pushButtonWindSpd->setGeometry(QRect(0, 250, 201, 25));
        pushButtonWindDir = new QPushButton(centralWidget);
        pushButtonWindDir->setObjectName(QString::fromUtf8("pushButtonWindDir"));
        pushButtonWindDir->setGeometry(QRect(210, 250, 221, 25));
        pushButtonAirT = new QPushButton(centralWidget);
        pushButtonAirT->setObjectName(QString::fromUtf8("pushButtonAirT"));
        pushButtonAirT->setGeometry(QRect(410, 350, 181, 25));
        pushButtonDpT = new QPushButton(centralWidget);
        pushButtonDpT->setObjectName(QString::fromUtf8("pushButtonDpT"));
        pushButtonDpT->setGeometry(QRect(630, 660, 231, 25));
        pushButtonRhP = new QPushButton(centralWidget);
        pushButtonRhP->setObjectName(QString::fromUtf8("pushButtonRhP"));
        pushButtonRhP->setGeometry(QRect(870, 660, 211, 25));
        pushButtonBaro = new QPushButton(centralWidget);
        pushButtonBaro->setObjectName(QString::fromUtf8("pushButtonBaro"));
        pushButtonBaro->setGeometry(QRect(410, 660, 191, 25));
        Dial = new QwtDial(centralWidget);
        Dial->setObjectName(QString::fromUtf8("Dial"));
        Dial->setGeometry(QRect(10, 0, 200, 200));
        Dial->setReadOnly(true);
        Dial->setLineWidth(4);
        Compass = new QwtCompass(centralWidget);
        Compass->setObjectName(QString::fromUtf8("Compass"));
        Compass->setGeometry(QRect(230, 0, 200, 200));
        Compass->setReadOnly(true);
        Compass->setLineWidth(4);
        CompassCmgT = new QwtCompass(centralWidget);
        CompassCmgT->setObjectName(QString::fromUtf8("CompassCmgT"));
        CompassCmgT->setGeometry(QRect(650, 0, 200, 200));
        CompassCmgT->setReadOnly(true);
        CompassCmgT->setLineWidth(4);
        CompassCmgT->setMode(QwtDial::RotateScale);
        DialBoatSpd = new QwtDial(centralWidget);
        DialBoatSpd->setObjectName(QString::fromUtf8("DialBoatSpd"));
        DialBoatSpd->setGeometry(QRect(870, 0, 200, 200));
        DialBoatSpd->setReadOnly(true);
        DialBoatSpd->setLineWidth(4);
        boatVmgKMinData = new QLabel(centralWidget);
        boatVmgKMinData->setObjectName(QString::fromUtf8("boatVmgKMinData"));
        boatVmgKMinData->setGeometry(QRect(890, 230, 61, 16));
        boatVmgKData = new QLabel(centralWidget);
        boatVmgKData->setObjectName(QString::fromUtf8("boatVmgKData"));
        boatVmgKData->setGeometry(QRect(1030, 210, 51, 20));
        boatVmgKMaxData = new QLabel(centralWidget);
        boatVmgKMaxData->setObjectName(QString::fromUtf8("boatVmgKMaxData"));
        boatVmgKMaxData->setGeometry(QRect(1030, 230, 51, 20));
        baroPressLabel_4 = new QLabel(centralWidget);
        baroPressLabel_4->setObjectName(QString::fromUtf8("baroPressLabel_4"));
        baroPressLabel_4->setGeometry(QRect(870, 210, 141, 16));
        pushButtonBoatVmgK = new QPushButton(centralWidget);
        pushButtonBoatVmgK->setObjectName(QString::fromUtf8("pushButtonBoatVmgK"));
        pushButtonBoatVmgK->setGeometry(QRect(870, 250, 211, 25));
        pushButtonBoatCmgT = new QPushButton(centralWidget);
        pushButtonBoatCmgT->setObjectName(QString::fromUtf8("pushButtonBoatCmgT"));
        pushButtonBoatCmgT->setGeometry(QRect(650, 250, 211, 25));
        boatCmgTData = new QLabel(centralWidget);
        boatCmgTData->setObjectName(QString::fromUtf8("boatCmgTData"));
        boatCmgTData->setGeometry(QRect(790, 210, 51, 20));
        boatCmgTMaxData = new QLabel(centralWidget);
        boatCmgTMaxData->setObjectName(QString::fromUtf8("boatCmgTMaxData"));
        boatCmgTMaxData->setGeometry(QRect(790, 230, 61, 20));
        boatCmgTMinData = new QLabel(centralWidget);
        boatCmgTMinData->setObjectName(QString::fromUtf8("boatCmgTMinData"));
        boatCmgTMinData->setGeometry(QRect(670, 230, 61, 16));
        baroPressLabel_5 = new QLabel(centralWidget);
        baroPressLabel_5->setObjectName(QString::fromUtf8("baroPressLabel_5"));
        baroPressLabel_5->setGeometry(QRect(650, 210, 131, 16));
        baroPressLabel_6 = new QLabel(centralWidget);
        baroPressLabel_6->setObjectName(QString::fromUtf8("baroPressLabel_6"));
        baroPressLabel_6->setGeometry(QRect(630, 520, 141, 20));
        relWindDirMinData = new QLabel(centralWidget);
        relWindDirMinData->setObjectName(QString::fromUtf8("relWindDirMinData"));
        relWindDirMinData->setGeometry(QRect(660, 540, 61, 16));
        CompassRelWind = new QwtCompass(centralWidget);
        CompassRelWind->setObjectName(QString::fromUtf8("CompassRelWind"));
        CompassRelWind->setGeometry(QRect(640, 310, 200, 200));
        CompassRelWind->setReadOnly(true);
        CompassRelWind->setLineWidth(4);
        CompassRelWind->setMode(QwtDial::RotateNeedle);
        pushButtonRelWindDir = new QPushButton(centralWidget);
        pushButtonRelWindDir->setObjectName(QString::fromUtf8("pushButtonRelWindDir"));
        pushButtonRelWindDir->setGeometry(QRect(630, 560, 231, 25));
        relWindDirData = new QLabel(centralWidget);
        relWindDirData->setObjectName(QString::fromUtf8("relWindDirData"));
        relWindDirData->setGeometry(QRect(780, 520, 51, 20));
        relWindDirMaxData = new QLabel(centralWidget);
        relWindDirMaxData->setObjectName(QString::fromUtf8("relWindDirMaxData"));
        relWindDirMaxData->setGeometry(QRect(780, 540, 61, 20));
        boatHdgMData = new QLabel(centralWidget);
        boatHdgMData->setObjectName(QString::fromUtf8("boatHdgMData"));
        boatHdgMData->setGeometry(QRect(580, 210, 51, 20));
        boatHdgMMaxData = new QLabel(centralWidget);
        boatHdgMMaxData->setObjectName(QString::fromUtf8("boatHdgMMaxData"));
        boatHdgMMaxData->setGeometry(QRect(580, 230, 61, 20));
        CompassMagHdg = new QwtCompass(centralWidget);
        CompassMagHdg->setObjectName(QString::fromUtf8("CompassMagHdg"));
        CompassMagHdg->setGeometry(QRect(440, 0, 200, 200));
        CompassMagHdg->setReadOnly(true);
        CompassMagHdg->setLineWidth(4);
        CompassMagHdg->setMode(QwtDial::RotateScale);
        baroPressLabel_7 = new QLabel(centralWidget);
        baroPressLabel_7->setObjectName(QString::fromUtf8("baroPressLabel_7"));
        baroPressLabel_7->setGeometry(QRect(440, 210, 131, 16));
        pushButtonBoatHdgM = new QPushButton(centralWidget);
        pushButtonBoatHdgM->setObjectName(QString::fromUtf8("pushButtonBoatHdgM"));
        pushButtonBoatHdgM->setGeometry(QRect(440, 250, 201, 25));
        boatHdgMMinData = new QLabel(centralWidget);
        boatHdgMMinData->setObjectName(QString::fromUtf8("boatHdgMMinData"));
        boatHdgMMinData->setGeometry(QRect(460, 230, 61, 16));
        DialRelWindSpd = new QwtDial(centralWidget);
        DialRelWindSpd->setObjectName(QString::fromUtf8("DialRelWindSpd"));
        DialRelWindSpd->setGeometry(QRect(880, 310, 200, 200));
        DialRelWindSpd->setReadOnly(true);
        DialRelWindSpd->setLineWidth(4);
        windSpeedLabel_2 = new QLabel(centralWidget);
        windSpeedLabel_2->setObjectName(QString::fromUtf8("windSpeedLabel_2"));
        windSpeedLabel_2->setGeometry(QRect(870, 520, 151, 20));
        relWindSpeedMaxData = new QLabel(centralWidget);
        relWindSpeedMaxData->setObjectName(QString::fromUtf8("relWindSpeedMaxData"));
        relWindSpeedMaxData->setGeometry(QRect(1020, 540, 71, 16));
        relWindSpeedMinData = new QLabel(centralWidget);
        relWindSpeedMinData->setObjectName(QString::fromUtf8("relWindSpeedMinData"));
        relWindSpeedMinData->setGeometry(QRect(900, 540, 81, 16));
        relWindSpeedData = new QLabel(centralWidget);
        relWindSpeedData->setObjectName(QString::fromUtf8("relWindSpeedData"));
        relWindSpeedData->setGeometry(QRect(1020, 520, 61, 16));
        pushButtonRelWindSpd = new QPushButton(centralWidget);
        pushButtonRelWindSpd->setObjectName(QString::fromUtf8("pushButtonRelWindSpd"));
        pushButtonRelWindSpd->setGeometry(QRect(870, 560, 211, 25));
        utcTimeVal = new QLabel(centralWidget);
        utcTimeVal->setObjectName(QString::fromUtf8("utcTimeVal"));
        utcTimeVal->setGeometry(QRect(1140, 0, 121, 20));
        baroPressLabel_8 = new QLabel(centralWidget);
        baroPressLabel_8->setObjectName(QString::fromUtf8("baroPressLabel_8"));
        baroPressLabel_8->setGeometry(QRect(1090, 0, 51, 20));
        utcTimeVal_2 = new QLabel(centralWidget);
        utcTimeVal_2->setObjectName(QString::fromUtf8("utcTimeVal_2"));
        utcTimeVal_2->setGeometry(QRect(1030, -530, 91, 16));
        pushButtonWindSpdAlarm = new QPushButton(centralWidget);
        pushButtonWindSpdAlarm->setObjectName(QString::fromUtf8("pushButtonWindSpdAlarm"));
        pushButtonWindSpdAlarm->setGeometry(QRect(0, 280, 81, 25));
        pushButtonWindSpdAlarm->setCheckable(true);
        lineEditWindSpdLow = new QLineEdit(centralWidget);
        lineEditWindSpdLow->setObjectName(QString::fromUtf8("lineEditWindSpdLow"));
        lineEditWindSpdLow->setGeometry(QRect(80, 280, 51, 24));
        lineEditWindSpdHigh = new QLineEdit(centralWidget);
        lineEditWindSpdHigh->setObjectName(QString::fromUtf8("lineEditWindSpdHigh"));
        lineEditWindSpdHigh->setGeometry(QRect(140, 280, 61, 24));
        lineEditBoatHdgHigh = new QLineEdit(centralWidget);
        lineEditBoatHdgHigh->setObjectName(QString::fromUtf8("lineEditBoatHdgHigh"));
        lineEditBoatHdgHigh->setGeometry(QRect(590, 280, 51, 24));
        pushButtonBoatHdgAlarm = new QPushButton(centralWidget);
        pushButtonBoatHdgAlarm->setObjectName(QString::fromUtf8("pushButtonBoatHdgAlarm"));
        pushButtonBoatHdgAlarm->setGeometry(QRect(440, 280, 81, 25));
        pushButtonBoatHdgAlarm->setCheckable(true);
        lineEditBoatHdgLow = new QLineEdit(centralWidget);
        lineEditBoatHdgLow->setObjectName(QString::fromUtf8("lineEditBoatHdgLow"));
        lineEditBoatHdgLow->setGeometry(QRect(530, 280, 51, 24));
        lineEditWindDirLow = new QLineEdit(centralWidget);
        lineEditWindDirLow->setObjectName(QString::fromUtf8("lineEditWindDirLow"));
        lineEditWindDirLow->setGeometry(QRect(300, 280, 61, 24));
        lineEditWindDirHigh = new QLineEdit(centralWidget);
        lineEditWindDirHigh->setObjectName(QString::fromUtf8("lineEditWindDirHigh"));
        lineEditWindDirHigh->setGeometry(QRect(370, 280, 61, 24));
        pushButtonWindDirAlarm = new QPushButton(centralWidget);
        pushButtonWindDirAlarm->setObjectName(QString::fromUtf8("pushButtonWindDirAlarm"));
        pushButtonWindDirAlarm->setGeometry(QRect(210, 280, 81, 25));
        pushButtonWindDirAlarm->setCheckable(true);
        radioButtonWindAlarm = new QRadioButton(centralWidget);
        radioButtonWindAlarm->setObjectName(QString::fromUtf8("radioButtonWindAlarm"));
        radioButtonWindAlarm->setEnabled(true);
        radioButtonWindAlarm->setGeometry(QRect(0, 180, 16, 20));
        radioButtonWindAlarm->setAutoRepeat(false);
        radioButtonWindAlarm->setAutoExclusive(false);
        radioButtonWindDirAlarm = new QRadioButton(centralWidget);
        radioButtonWindDirAlarm->setObjectName(QString::fromUtf8("radioButtonWindDirAlarm"));
        radioButtonWindDirAlarm->setEnabled(true);
        radioButtonWindDirAlarm->setGeometry(QRect(210, 180, 16, 20));
        radioButtonWindDirAlarm->setChecked(false);
        radioButtonWindDirAlarm->setAutoExclusive(false);
        radioButtonBoatHdgAlarm = new QRadioButton(centralWidget);
        radioButtonBoatHdgAlarm->setObjectName(QString::fromUtf8("radioButtonBoatHdgAlarm"));
        radioButtonBoatHdgAlarm->setEnabled(true);
        radioButtonBoatHdgAlarm->setGeometry(QRect(440, 180, 16, 20));
        radioButtonBoatHdgAlarm->setChecked(false);
        radioButtonBoatHdgAlarm->setAutoExclusive(false);
        lineEditBoatCmgLow = new QLineEdit(centralWidget);
        lineEditBoatCmgLow->setObjectName(QString::fromUtf8("lineEditBoatCmgLow"));
        lineEditBoatCmgLow->setGeometry(QRect(740, 280, 51, 24));
        lineEditBoatCmgHigh = new QLineEdit(centralWidget);
        lineEditBoatCmgHigh->setObjectName(QString::fromUtf8("lineEditBoatCmgHigh"));
        lineEditBoatCmgHigh->setGeometry(QRect(800, 280, 61, 24));
        pushButtonBoatCmgAlarm = new QPushButton(centralWidget);
        pushButtonBoatCmgAlarm->setObjectName(QString::fromUtf8("pushButtonBoatCmgAlarm"));
        pushButtonBoatCmgAlarm->setGeometry(QRect(650, 280, 81, 25));
        pushButtonBoatCmgAlarm->setCheckable(true);
        pushButtonBoatSogAlarm = new QPushButton(centralWidget);
        pushButtonBoatSogAlarm->setObjectName(QString::fromUtf8("pushButtonBoatSogAlarm"));
        pushButtonBoatSogAlarm->setGeometry(QRect(870, 280, 81, 25));
        pushButtonBoatSogAlarm->setCheckable(true);
        lineEditBoatSogLow = new QLineEdit(centralWidget);
        lineEditBoatSogLow->setObjectName(QString::fromUtf8("lineEditBoatSogLow"));
        lineEditBoatSogLow->setGeometry(QRect(960, 280, 51, 24));
        lineEditBoatSogHigh = new QLineEdit(centralWidget);
        lineEditBoatSogHigh->setObjectName(QString::fromUtf8("lineEditBoatSogHigh"));
        lineEditBoatSogHigh->setGeometry(QRect(1020, 280, 61, 24));
        radioButtonBoatCmgAlarm = new QRadioButton(centralWidget);
        radioButtonBoatCmgAlarm->setObjectName(QString::fromUtf8("radioButtonBoatCmgAlarm"));
        radioButtonBoatCmgAlarm->setEnabled(true);
        radioButtonBoatCmgAlarm->setGeometry(QRect(650, 180, 16, 20));
        radioButtonBoatCmgAlarm->setChecked(false);
        radioButtonBoatCmgAlarm->setAutoExclusive(false);
        radioButtonBoatSogAlarm = new QRadioButton(centralWidget);
        radioButtonBoatSogAlarm->setObjectName(QString::fromUtf8("radioButtonBoatSogAlarm"));
        radioButtonBoatSogAlarm->setEnabled(true);
        radioButtonBoatSogAlarm->setGeometry(QRect(870, 180, 16, 20));
        radioButtonBoatSogAlarm->setChecked(false);
        radioButtonBoatSogAlarm->setAutoExclusive(false);
        pushButtonRelWindDirAlarm = new QPushButton(centralWidget);
        pushButtonRelWindDirAlarm->setObjectName(QString::fromUtf8("pushButtonRelWindDirAlarm"));
        pushButtonRelWindDirAlarm->setGeometry(QRect(630, 590, 81, 25));
        pushButtonRelWindDirAlarm->setCheckable(true);
        lineEditRelWindDirLow = new QLineEdit(centralWidget);
        lineEditRelWindDirLow->setObjectName(QString::fromUtf8("lineEditRelWindDirLow"));
        lineEditRelWindDirLow->setGeometry(QRect(720, 590, 61, 24));
        lineEditRelWindDirHigh = new QLineEdit(centralWidget);
        lineEditRelWindDirHigh->setObjectName(QString::fromUtf8("lineEditRelWindDirHigh"));
        lineEditRelWindDirHigh->setGeometry(QRect(790, 590, 71, 24));
        lineEditRelWindSpdHigh = new QLineEdit(centralWidget);
        lineEditRelWindSpdHigh->setObjectName(QString::fromUtf8("lineEditRelWindSpdHigh"));
        lineEditRelWindSpdHigh->setGeometry(QRect(1020, 590, 61, 24));
        pushButtonRelWindSpdAlarm = new QPushButton(centralWidget);
        pushButtonRelWindSpdAlarm->setObjectName(QString::fromUtf8("pushButtonRelWindSpdAlarm"));
        pushButtonRelWindSpdAlarm->setGeometry(QRect(870, 590, 81, 25));
        pushButtonRelWindSpdAlarm->setCheckable(true);
        lineEditRelWindSpdLow = new QLineEdit(centralWidget);
        lineEditRelWindSpdLow->setObjectName(QString::fromUtf8("lineEditRelWindSpdLow"));
        lineEditRelWindSpdLow->setGeometry(QRect(960, 590, 51, 24));
        radioButtonRelWindSpdAlarm = new QRadioButton(centralWidget);
        radioButtonRelWindSpdAlarm->setObjectName(QString::fromUtf8("radioButtonRelWindSpdAlarm"));
        radioButtonRelWindSpdAlarm->setEnabled(true);
        radioButtonRelWindSpdAlarm->setGeometry(QRect(870, 480, 16, 20));
        radioButtonRelWindSpdAlarm->setChecked(false);
        radioButtonRelWindSpdAlarm->setAutoExclusive(false);
        radioButtonRelWindDirAlarm = new QRadioButton(centralWidget);
        radioButtonRelWindDirAlarm->setObjectName(QString::fromUtf8("radioButtonRelWindDirAlarm"));
        radioButtonRelWindDirAlarm->setEnabled(true);
        radioButtonRelWindDirAlarm->setGeometry(QRect(630, 490, 16, 20));
        radioButtonRelWindDirAlarm->setChecked(false);
        radioButtonRelWindDirAlarm->setAutoExclusive(false);
        lineEditBoatSogLow_4 = new QLineEdit(centralWidget);
        lineEditBoatSogLow_4->setObjectName(QString::fromUtf8("lineEditBoatSogLow_4"));
        lineEditBoatSogLow_4->setGeometry(QRect(1040, 1250, 51, 24));
        pushButtonWaterT = new QPushButton(centralWidget);
        pushButtonWaterT->setObjectName(QString::fromUtf8("pushButtonWaterT"));
        pushButtonWaterT->setGeometry(QRect(410, 450, 181, 25));
        waterTempMaxData = new QLabel(centralWidget);
        waterTempMaxData->setObjectName(QString::fromUtf8("waterTempMaxData"));
        waterTempMaxData->setGeometry(QRect(520, 430, 91, 20));
        waterTempLabel = new QLabel(centralWidget);
        waterTempLabel->setObjectName(QString::fromUtf8("waterTempLabel"));
        waterTempLabel->setGeometry(QRect(410, 410, 111, 16));
        waterTempMinData = new QLabel(centralWidget);
        waterTempMinData->setObjectName(QString::fromUtf8("waterTempMinData"));
        waterTempMinData->setGeometry(QRect(430, 430, 91, 20));
        waterTempData = new QLabel(centralWidget);
        waterTempData->setObjectName(QString::fromUtf8("waterTempData"));
        waterTempData->setGeometry(QRect(520, 410, 81, 16));
        waterDepthData = new QLabel(centralWidget);
        waterDepthData->setObjectName(QString::fromUtf8("waterDepthData"));
        waterDepthData->setGeometry(QRect(530, 520, 81, 16));
        waterDepthMaxData = new QLabel(centralWidget);
        waterDepthMaxData->setObjectName(QString::fromUtf8("waterDepthMaxData"));
        waterDepthMaxData->setGeometry(QRect(530, 540, 91, 20));
        pushButtonWaterD = new QPushButton(centralWidget);
        pushButtonWaterD->setObjectName(QString::fromUtf8("pushButtonWaterD"));
        pushButtonWaterD->setGeometry(QRect(410, 560, 191, 25));
        waterTempLabel_2 = new QLabel(centralWidget);
        waterTempLabel_2->setObjectName(QString::fromUtf8("waterTempLabel_2"));
        waterTempLabel_2->setGeometry(QRect(410, 520, 111, 16));
        waterDepthMinData = new QLabel(centralWidget);
        waterDepthMinData->setObjectName(QString::fromUtf8("waterDepthMinData"));
        waterDepthMinData->setGeometry(QRect(430, 540, 101, 20));
        baroPressLabel_9 = new QLabel(centralWidget);
        baroPressLabel_9->setObjectName(QString::fromUtf8("baroPressLabel_9"));
        baroPressLabel_9->setGeometry(QRect(1090, 50, 111, 20));
        baroPressLabel_10 = new QLabel(centralWidget);
        baroPressLabel_10->setObjectName(QString::fromUtf8("baroPressLabel_10"));
        baroPressLabel_10->setGeometry(QRect(1090, 70, 111, 20));
        pushButtonGlobalReset = new QPushButton(centralWidget);
        pushButtonGlobalReset->setObjectName(QString::fromUtf8("pushButtonGlobalReset"));
        pushButtonGlobalReset->setGeometry(QRect(1090, 160, 191, 25));
        globalResetLabel = new QLabel(centralWidget);
        globalResetLabel->setObjectName(QString::fromUtf8("globalResetLabel"));
        globalResetLabel->setGeometry(QRect(1090, 120, 131, 20));
        globalResetVal = new QLabel(centralWidget);
        globalResetVal->setObjectName(QString::fromUtf8("globalResetVal"));
        globalResetVal->setGeometry(QRect(1100, 140, 111, 20));
        textBrowserBaro = new QTextBrowser(centralWidget);
        textBrowserBaro->setObjectName(QString::fromUtf8("textBrowserBaro"));
        textBrowserBaro->setGeometry(QRect(1090, 210, 201, 481));
        baroHourlyLabel = new QLabel(centralWidget);
        baroHourlyLabel->setObjectName(QString::fromUtf8("baroHourlyLabel"));
        baroHourlyLabel->setGeometry(QRect(1090, 190, 191, 20));
        positionLatDData = new QLabel(centralWidget);
        positionLatDData->setObjectName(QString::fromUtf8("positionLatDData"));
        positionLatDData->setGeometry(QRect(60, 340, 50, 16));
        windSpeedLabel_3 = new QLabel(centralWidget);
        windSpeedLabel_3->setObjectName(QString::fromUtf8("windSpeedLabel_3"));
        windSpeedLabel_3->setGeometry(QRect(20, 340, 40, 16));
        positionLonDData = new QLabel(centralWidget);
        positionLonDData->setObjectName(QString::fromUtf8("positionLonDData"));
        positionLonDData->setGeometry(QRect(60, 360, 50, 16));
        positionLatMData = new QLabel(centralWidget);
        positionLatMData->setObjectName(QString::fromUtf8("positionLatMData"));
        positionLatMData->setGeometry(QRect(110, 340, 90, 16));
        positionLonMData = new QLabel(centralWidget);
        positionLonMData->setObjectName(QString::fromUtf8("positionLonMData"));
        positionLonMData->setGeometry(QRect(110, 360, 90, 16));
        windSpeedLabel_4 = new QLabel(centralWidget);
        windSpeedLabel_4->setObjectName(QString::fromUtf8("windSpeedLabel_4"));
        windSpeedLabel_4->setGeometry(QRect(20, 360, 41, 16));
        windSpeedLabel_5 = new QLabel(centralWidget);
        windSpeedLabel_5->setObjectName(QString::fromUtf8("windSpeedLabel_5"));
        windSpeedLabel_5->setGeometry(QRect(0, 310, 150, 16));
        windSpeedLabel_6 = new QLabel(centralWidget);
        windSpeedLabel_6->setObjectName(QString::fromUtf8("windSpeedLabel_6"));
        windSpeedLabel_6->setGeometry(QRect(210, 310, 161, 16));
        lineEditRefPosLatM = new QLineEdit(centralWidget);
        lineEditRefPosLatM->setObjectName(QString::fromUtf8("lineEditRefPosLatM"));
        lineEditRefPosLatM->setGeometry(QRect(300, 330, 91, 24));
        lineEditRefPosLatD = new QLineEdit(centralWidget);
        lineEditRefPosLatD->setObjectName(QString::fromUtf8("lineEditRefPosLatD"));
        lineEditRefPosLatD->setGeometry(QRect(230, 330, 61, 24));
        lineEditRefPosLonM = new QLineEdit(centralWidget);
        lineEditRefPosLonM->setObjectName(QString::fromUtf8("lineEditRefPosLonM"));
        lineEditRefPosLonM->setGeometry(QRect(300, 350, 91, 24));
        lineEditRefPosLonD = new QLineEdit(centralWidget);
        lineEditRefPosLonD->setObjectName(QString::fromUtf8("lineEditRefPosLonD"));
        lineEditRefPosLonD->setGeometry(QRect(230, 350, 61, 24));
        pushButtonSetRefPosHere = new QPushButton(centralWidget);
        pushButtonSetRefPosHere->setObjectName(QString::fromUtf8("pushButtonSetRefPosHere"));
        pushButtonSetRefPosHere->setGeometry(QRect(210, 380, 191, 25));
        pushButtonSetRefPosHere->setCheckable(false);
        positionDistanceF = new QLabel(centralWidget);
        positionDistanceF->setObjectName(QString::fromUtf8("positionDistanceF"));
        positionDistanceF->setGeometry(QRect(110, 410, 101, 20));
        windSpeedLabel_7 = new QLabel(centralWidget);
        windSpeedLabel_7->setObjectName(QString::fromUtf8("windSpeedLabel_7"));
        windSpeedLabel_7->setGeometry(QRect(0, 410, 111, 20));
        lineEditPositionHigh = new QLineEdit(centralWidget);
        lineEditPositionHigh->setObjectName(QString::fromUtf8("lineEditPositionHigh"));
        lineEditPositionHigh->setGeometry(QRect(140, 380, 61, 24));
        lineEditPositionLow = new QLineEdit(centralWidget);
        lineEditPositionLow->setObjectName(QString::fromUtf8("lineEditPositionLow"));
        lineEditPositionLow->setGeometry(QRect(80, 380, 51, 24));
        pushButtonPositionAlarm = new QPushButton(centralWidget);
        pushButtonPositionAlarm->setObjectName(QString::fromUtf8("pushButtonPositionAlarm"));
        pushButtonPositionAlarm->setGeometry(QRect(0, 380, 81, 25));
        pushButtonPositionAlarm->setCheckable(true);
        pushButtonPositionAlarm->setChecked(false);
        pushButtonPositionAlarm->setAutoExclusive(false);
        windSpeedLabel_8 = new QLabel(centralWidget);
        windSpeedLabel_8->setObjectName(QString::fromUtf8("windSpeedLabel_8"));
        windSpeedLabel_8->setGeometry(QRect(0, 430, 111, 20));
        positionMaxDistanceF = new QLabel(centralWidget);
        positionMaxDistanceF->setObjectName(QString::fromUtf8("positionMaxDistanceF"));
        positionMaxDistanceF->setGeometry(QRect(110, 430, 101, 20));
        windSpeedLabel_9 = new QLabel(centralWidget);
        windSpeedLabel_9->setObjectName(QString::fromUtf8("windSpeedLabel_9"));
        windSpeedLabel_9->setGeometry(QRect(210, 410, 111, 20));
        windSpeedLabel_10 = new QLabel(centralWidget);
        windSpeedLabel_10->setObjectName(QString::fromUtf8("windSpeedLabel_10"));
        windSpeedLabel_10->setGeometry(QRect(210, 430, 111, 20));
        positionNSDistanceF = new QLabel(centralWidget);
        positionNSDistanceF->setObjectName(QString::fromUtf8("positionNSDistanceF"));
        positionNSDistanceF->setGeometry(QRect(320, 410, 91, 20));
        positionWEDistanceF = new QLabel(centralWidget);
        positionWEDistanceF->setObjectName(QString::fromUtf8("positionWEDistanceF"));
        positionWEDistanceF->setGeometry(QRect(320, 430, 91, 20));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1297, 27));
        menuProgram = new QMenu(menuBar);
        menuProgram->setObjectName(QString::fromUtf8("menuProgram"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuProgram->menuAction());
        menuProgram->addAction(actionQuit);

        retranslateUi(MainWindow);
        QObject::connect(actionQuit, SIGNAL(activated()), MainWindow, SLOT(close()));

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        actionQuit->setText(QApplication::translate("MainWindow", "Quit", 0, QApplication::UnicodeUTF8));
        hostLabel->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        portLabel->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonChangeHost->setText(QApplication::translate("MainWindow", "Change Host/Port", 0, QApplication::UnicodeUTF8));
        pushButtonStart->setText(QApplication::translate("MainWindow", "Start Program", 0, QApplication::UnicodeUTF8));
        windSpeedLabel->setText(QApplication::translate("MainWindow", "Wind Spd Knots:", 0, QApplication::UnicodeUTF8));
        windSpeedData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windDirLabel->setText(QApplication::translate("MainWindow", "Wind Direction True:", 0, QApplication::UnicodeUTF8));
        windDirData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        airTempLabel->setText(QApplication::translate("MainWindow", "Air Temp F:", 0, QApplication::UnicodeUTF8));
        airTempData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        dpTempData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        dpTempLabel->setText(QApplication::translate("MainWindow", "Dew Point F:", 0, QApplication::UnicodeUTF8));
        rhPercentLabel->setText(QApplication::translate("MainWindow", "Relative Humidity:", 0, QApplication::UnicodeUTF8));
        rhPercentData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel->setText(QApplication::translate("MainWindow", "Barometer mB:", 0, QApplication::UnicodeUTF8));
        windSpeedMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windDirMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windDirMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        airTempMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        airTempMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        dpTempMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        dpTempMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        rhPercentMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        rhPercentMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonWindSpd->setText(QApplication::translate("MainWindow", "Reset Wind Speed", 0, QApplication::UnicodeUTF8));
        pushButtonWindDir->setText(QApplication::translate("MainWindow", "Reset Wind Direction", 0, QApplication::UnicodeUTF8));
        pushButtonAirT->setText(QApplication::translate("MainWindow", "Reset Air Temperature", 0, QApplication::UnicodeUTF8));
        pushButtonDpT->setText(QApplication::translate("MainWindow", "Reset Dew Point", 0, QApplication::UnicodeUTF8));
        pushButtonRhP->setText(QApplication::translate("MainWindow", "Reset Humidity", 0, QApplication::UnicodeUTF8));
        pushButtonBaro->setText(QApplication::translate("MainWindow", "Reset Barometer", 0, QApplication::UnicodeUTF8));
        boatVmgKMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatVmgKData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatVmgKMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel_4->setText(QApplication::translate("MainWindow", "Boat SOG Knots:", 0, QApplication::UnicodeUTF8));
        pushButtonBoatVmgK->setText(QApplication::translate("MainWindow", "Reset Boat SOG", 0, QApplication::UnicodeUTF8));
        pushButtonBoatCmgT->setText(QApplication::translate("MainWindow", "Reset Boat CMG", 0, QApplication::UnicodeUTF8));
        boatCmgTData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatCmgTMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatCmgTMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel_5->setText(QApplication::translate("MainWindow", "Boat CMG M:", 0, QApplication::UnicodeUTF8));
        baroPressLabel_6->setText(QApplication::translate("MainWindow", "Relative Wind Dir", 0, QApplication::UnicodeUTF8));
        relWindDirMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonRelWindDir->setText(QApplication::translate("MainWindow", "Reset Relative Wind Dir", 0, QApplication::UnicodeUTF8));
        relWindDirData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        relWindDirMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatHdgMData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        boatHdgMMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel_7->setText(QApplication::translate("MainWindow", "Boat Heading M:", 0, QApplication::UnicodeUTF8));
        pushButtonBoatHdgM->setText(QApplication::translate("MainWindow", "Reset Boat Heading", 0, QApplication::UnicodeUTF8));
        boatHdgMMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_2->setText(QApplication::translate("MainWindow", "Relative Wind Spd:", 0, QApplication::UnicodeUTF8));
        relWindSpeedMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        relWindSpeedMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        relWindSpeedData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonRelWindSpd->setText(QApplication::translate("MainWindow", "Reset Relative Wind Spd", 0, QApplication::UnicodeUTF8));
        utcTimeVal->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel_8->setText(QApplication::translate("MainWindow", "UTC:", 0, QApplication::UnicodeUTF8));
        utcTimeVal_2->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonWindSpdAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        pushButtonBoatHdgAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        pushButtonWindDirAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        radioButtonWindAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        radioButtonWindDirAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        radioButtonBoatHdgAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        pushButtonBoatCmgAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        pushButtonBoatSogAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        radioButtonBoatCmgAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        radioButtonBoatSogAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        pushButtonRelWindDirAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        pushButtonRelWindSpdAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        radioButtonRelWindSpdAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        radioButtonRelWindDirAlarm->setText(QApplication::translate("MainWindow", "RadioButton", 0, QApplication::UnicodeUTF8));
        pushButtonWaterT->setText(QApplication::translate("MainWindow", "Reset Water Temp", 0, QApplication::UnicodeUTF8));
        waterTempMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        waterTempLabel->setText(QApplication::translate("MainWindow", "Water Temp F:", 0, QApplication::UnicodeUTF8));
        waterTempMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        waterTempData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        waterDepthData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        waterDepthMaxData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        pushButtonWaterD->setText(QApplication::translate("MainWindow", "Reset Water Depth", 0, QApplication::UnicodeUTF8));
        waterTempLabel_2->setText(QApplication::translate("MainWindow", "Water Depth F:", 0, QApplication::UnicodeUTF8));
        waterDepthMinData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroPressLabel_9->setText(QApplication::translate("MainWindow", "Server Host:", 0, QApplication::UnicodeUTF8));
        baroPressLabel_10->setText(QApplication::translate("MainWindow", "Server Port:", 0, QApplication::UnicodeUTF8));
        pushButtonGlobalReset->setText(QApplication::translate("MainWindow", "Global Reset Min/Max", 0, QApplication::UnicodeUTF8));
        globalResetLabel->setText(QApplication::translate("MainWindow", "Last Reset UTC:", 0, QApplication::UnicodeUTF8));
        globalResetVal->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        baroHourlyLabel->setText(QApplication::translate("MainWindow", "Hourly Barometer Log:", 0, QApplication::UnicodeUTF8));
        positionLatDData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_3->setText(QApplication::translate("MainWindow", "Lat:", 0, QApplication::UnicodeUTF8));
        positionLonDData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        positionLatMData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        positionLonMData->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_4->setText(QApplication::translate("MainWindow", "Lon:", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_5->setText(QApplication::translate("MainWindow", "Current Position:", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_6->setText(QApplication::translate("MainWindow", "Reference Position:", 0, QApplication::UnicodeUTF8));
        lineEditRefPosLatM->setText(QApplication::translate("MainWindow", "N/A", 0, QApplication::UnicodeUTF8));
        lineEditRefPosLatD->setText(QApplication::translate("MainWindow", "N/A", 0, QApplication::UnicodeUTF8));
        lineEditRefPosLonM->setText(QApplication::translate("MainWindow", "N/A", 0, QApplication::UnicodeUTF8));
        lineEditRefPosLonD->setText(QApplication::translate("MainWindow", "N/A", 0, QApplication::UnicodeUTF8));
        pushButtonSetRefPosHere->setText(QApplication::translate("MainWindow", "Set Reference To Here", 0, QApplication::UnicodeUTF8));
        positionDistanceF->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_7->setText(QApplication::translate("MainWindow", "Distance Feet:", 0, QApplication::UnicodeUTF8));
        lineEditPositionHigh->setText(QApplication::translate("MainWindow", "200", 0, QApplication::UnicodeUTF8));
        lineEditPositionLow->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        pushButtonPositionAlarm->setText(QApplication::translate("MainWindow", "Set Alarm", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_8->setText(QApplication::translate("MainWindow", "Max Distance:", 0, QApplication::UnicodeUTF8));
        positionMaxDistanceF->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_9->setText(QApplication::translate("MainWindow", "N/S Distance:", 0, QApplication::UnicodeUTF8));
        windSpeedLabel_10->setText(QApplication::translate("MainWindow", "E/W Distance:", 0, QApplication::UnicodeUTF8));
        positionNSDistanceF->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        positionWEDistanceF->setText(QApplication::translate("MainWindow", "NA", 0, QApplication::UnicodeUTF8));
        menuProgram->setTitle(QApplication::translate("MainWindow", "Program", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
